--- #YAML:1.0
name:               Config-Auto
version:            0.29_02
abstract:           Magical config file parser
author:
    - Jos I. Boumans <kane@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::IniFiles:     0
    File::Spec::Functions:  0
    File::Temp:           0
    IO::String:           0
    Test::More:           0
    Text::ParseWords:     0
    YAML:                 0.67
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
