---
abstract: 'Magical config file parser'
author:
  - 'Jos I. Boumans <kane@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Auto
no_index:
  directory:
    - t
    - inc
requires:
  Config::IniFiles: 0
  File::Spec::Functions: 0
  File::Temp: 0
  IO::String: 0
  Test::More: 0
  Text::ParseWords: 0
  YAML: 0.67
resources:
  repository: https://github.com/jib/config-auto
version: 0.42
